// Events
export const GET_EVENTS = 'GET_EVENTS';
export const SELECT_EVENT = 'SELECT_EVENT';
export const REMOVE_SELECTED = 'REMOVE_SELECTED';
export const REMOVE_EVENT = 'REMOVE_EVENT';
export const CREATE_EVENT = 'CREATE_EVENT';
export const UPDATE_EVENT = 'UPDATE_EVENT';


// Form
export const FORM_DATE_CHANGE = 'FORM_DATE_CHANGE';
export const FORM_CHANGE = 'FORM_CHANGE';
export const FORM_CLEAR = 'FORM_CLEAR';
export const FORM_CLEAR_DATE = 'FORM_CLEAR_DATE';


// View
export const CHANGE_VIEW = 'CHANGE_VIEW';


// Loading
export const REQUEST_EVENTS = 'REQUEST_EVENTS';
export const SUCCESS_EVENTS = 'SUCCESS_EVENTS';
export const REQUEST_EVENT_CREATE = 'REQUEST_EVENT_CREATE';
export const SUCCESS_EVENT_CREATE = 'SUCCESS_EVENT_CREATE';
export const FAIL_EVENT_CREATE = 'FAIL_EVENT_CREATE';
export const SUCCESS_EVENT_UPDATE = 'SUCCESS_EVENT_UPDATE';
export const REQUEST_EVENT_UPDATE = 'REQUEST_EVENT_UPDATE';


// Filters
export const CHANGE_FILTER = 'CHANGE_FILTER';